# Generated by Django 5.2.15 on 2026-09-07 02:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField(help_text='Short summary shown on the catalogue card.')),
                ('inclusions', models.TextField(help_text='One item per line. Shown on the detail page.')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Price for a standard two bedroom, one bathroom property.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration_minutes', models.PositiveIntegerField(help_text='Used to work out whether two jobs for the same cleaner overlap.', validators=[django.core.validators.MinValueValidator(30)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services disappear from the catalogue but old bookings keep working.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
    ]
