# Generated by Django 5.2.15 on 2026-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='access_notes',
            field=models.TextField(blank=True, help_text='Optional. How the cleaner gets in. Cleared by the maintenance command 30 days after completion or cancellation.'),
        ),
    ]
